### ISSUE TITLE
How to run using GPU?

### ISSUE THREAD

**Issue by 777oxxo** [deepghs/waifuc#1]
![image](https://github.com/deepghs/waifuc/assets/91709915/dfbad1c4-2350-4715-a807-cdde901ef1b6)

**Comment by AsaTyr2018** [comment]
Same issue here with both versions:

PS C:\Users\someguy> pip install waifuc[gpu]
ERROR: Could not find a version that satisfies the requirement waifuc[gpu] (from versions: none)
ERROR: No matching distribution found for waifuc[gpu]
PS C:\Users\someguy> pip install waifuc
ERROR: Could not find a version that satisfies the requirement waifuc (from versions: none)
ERROR: No matching distribution found for waifuc

**Comment by narugo1992** [comment]
This package has not been released to PyPI yet.

So maybe you need to install it with source code.

(and i have to update readme, my bad XD
