### ISSUE TITLE
if i want download all image from Danbooru not olny in one keyword and i need classify those image what should i do？

### ISSUE THREAD

**Issue by Xian1yu2jun3** [deepghs/waifuc#14]
if i want download all image from Danbooru not olny in one keyword and i need classify those image what should i do？

**Comment by narugo1992** [comment]
Sorry, I didn't quite grasp your meaning. 

If you're looking for the entire dataset from the Danbooru website, we believe that for a dataset of this scale, any web scraping tools would be inappropriate. You might want to check this out: [https://gwern.net/danbooru2021#danbooru2020](https://gwern.net/danbooru2021#danbooru2020), and make sure you have enough storage space to download these publicly available datasets. 

Of course, this is just my interpretation of your inquiry. If I've misunderstood, please provide more information or, ideally, give examples for clarification.

**Comment by narugo1992** [comment]
PLEASE, DO NOT, try to download all images from danbooru with waifuc. You should download it from public dataset.

Closed due to not planned.
