### ISSUE TITLE
Handling Truncated Image Files in Waifuc using LocalSource

### ISSUE THREAD

**Issue by NebulaeWisdom** [deepghs/waifuc#15]
When using Waifuc, I discovered that using LocalSource may cause an error and exit when encountering images that have "part of the image is black, while the other part is normal". 
The Kohya script training raises an error message "image file is truncated". In my modified web crawler, I handle this issue by applying the following code snippet to check for errors when saving the file. If an error occurs, an exception is thrown, and the file is re-downloaded.
```
with Image.open(image_path) as image:
    try:
        image.load()
except (IOError, SyntaxError) as e:
    tqdm.write(f"校验下载图片{_id} {file_url} 时发生错误, error: {e}")
    return [0,row] #
```

 在使用waifuc的时候我发现，如果使用localSourse的话，在碰到部分图片是”图片一部分黑色，另一部分是正常的“的情况下，会导致报错退出。用kohya脚本训练提示”image file is truncated“ ，我在自己修改的爬虫上的处理方法是爬取到文件时用如下代码检测，如果报错就返回异常重新下载。

[error_image.zip](https://github.com/deepghs/waifuc/files/13715192/error_image.zip)

**Comment by narugo1992** [comment]
@NebulaeWisdom hi, try this #20
