### ISSUE TITLE
Why is it so slow in my 3090

### ISSUE THREAD

**Issue by jxhxgt** [deepghs/waifuc#46]
SaveExporter('E:\\xlzl\\reg\\1_zumi score__10\\新建文件夹'): 142it [06:20,  4.19s/it]
LocalSource('E:\\xlzl\\reg\\1_zumi score__10'): 140it [06:25,  1.57s/it]
Loading from 'E:\\xlzl\\reg\\1_zumi score__10':  13%|██████████▍                                                                      | 440/3433 [06:25<26:08,  1.91it/s] 
this‘s my code
from waifuc.action import ModeConvertAction
from waifuc.export import SaveExporter
from waifuc.source import LocalSource
from waifuc.action import NoMonochromeAction
from waifuc.action import ClassFilterAction
from waifuc.action import FaceCountAction
from waifuc.action import ThreeStageSplitAction, FilterSimilarAction

if __name__ == '__main__':
    source = LocalSource(r'E:\xlzl\reg\1_zumi score__10')
    source = source.attach(
        ModeConvertAction(mode='RGB', force_background='white'),NoMonochromeAction(),ClassFilterAction(['illustration', 'bangumi', '3D']),FilterSimilarAction(),FaceCountAction(1),
     ThreeStageSplitAction(),)

    source.export(SaveExporter(r'E:\xlzl\reg\1_zumi score__10\新建文件夹'))

**Comment by narugo1992** [comment]
i dont know what u mean slow? i think it's quite okay to have 2it/s when u using so many ai models to clean your dataset. dont expect to have 1000it/s even when u are using auto pipeline.

btw, do NOT use `3D`, it is `3d`. they are different, i think as a python user u should know that. 😄
