### ISSUE TITLE
Failed to obtain images from the video.

### ISSUE THREAD

**Issue by isco22** [deepghs/waifuc#53]
Failed to obtain images from the video.
SaveExporter('/data/dstdataset'): 0it [00:00, ?it/s]  ERROR:root:Video '/data/videos/18.mp4' is invalid, skipped
VideoSource('/data/videos/18.mp4'): 0it [00:03, ?it/s]
SaveExporter('/data/dstdataset'): 0it [00:03, ?it/s]

The video can be played, and there is no problem with the path.

从视频里面获取图像失败，
视频可以播放，路径没有问题。

**Comment by narugo1992** [comment]
closed due to a misusage.
