### ISSUE TITLE
Is this the tool you use to collect anime screenshots for the dataset?

### ISSUE THREAD

**Issue by Varkilister** [deepghs/waifuc#59]

**Comment by narugo1992** [comment]
@Varkilister hi, you mean the screencaps in https://huggingface.co/BangumiBase?

not this tools, maybe what u need is https://github.com/deepghs/cyberharem?tab=readme-ov-file#batch-process-anime-videos

the screepcap pipeline is based on waifuc, but waifuc is not the tools to create datasets in bangumibase
