### ISSUE TITLE
ONNX Runtime error

### ISSUE THREAD

**Issue by shimizu-izumi** [deepghs/waifuc#65]
I'm getting an ONNX Runtime error that CUDA_PATH is set but CUDA wasn't able to load even tho I have the correct CUDA version installed and use a 4090.

*************** EP Error ***************
EP Error D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:891 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasnt able to be loaded. Please install the correct version of CUDA andcuDNN as mentioned in the GPU requirements page  (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements),  make sure they're in the PATH, and that your GPU is supported.
 when using ['CUDAExecutionProvider', 'CPUExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
****************************************

My CUDA_PATH is set to `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8`

**Comment by shimizu-izumi** [comment]
Upgraded to CUDA 12.6, still the same error

**Comment by narugo1992** [comment]
no idea on this

just, plz, reinstall your whole environment, and use a conda to manage your dependency.

**Comment by shimizu-izumi** [comment]
I rarely use python so I simply used the integrated venv. But I guess I'll try conda

**Comment by AnAncientForce** [comment]
Any luck on this? I'm also using a 4090 and experiencing the same issue. I have installed CUDA Toolkit 12.6 and cuDNN 9.3.0. `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.6\bin` was automatically added to PATH, but `C:\Program Files\NVIDIA\CUDNN\v9.3\bin\12.6` was not so I added it manually. I'm using a python virtual environment with these packages:
* onnxruntime-gpu
* git+https://github.com/deepghs/waifuc.git@main#egg=waifuc[video]
* dghs-imgutils[gpu]

I cannot tell where I'm going wrong, I've also tried several different versions of CUDA but none of them have worked, this is the error message I've been getting from the very start:
```python
2024-08-17 09:12:23.6153922 [E:onnxruntime:Default, provider_bridge_ort.cc:1992 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1637 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "D:\Training Workflow\Video Extraction\.venv\lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

2024-08-17 09:12:23.6229792 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:965 onnxruntime::python::CreateExecutionProviderInstance] Failed to create CUDAExecutionProvider. Require cuDNN 9.* and CUDA 12.*, and the latest MSVC runtime. Please install all dependencies as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.
```

It runs perfectly on the CPU, but I would like the GPU for processing.

Also, is using conda any different from using venv?

**Comment by shimizu-izumi** [comment]
From my understanding Conda is something like venv but more complicated and advanced and it didn't work for me, I wasn't even able to activate the environment. but I'm still trying to get this to work

**Comment by AnAncientForce** [comment]
@shimizu-izumi After countless attempts, turned out that I was installing it incorrectly. I don't know about the newest version, but I followed this [tutorial](https://www.youtube.com/watch?v=KC9-9L7FgPc) and everything worked perfectly. However for me, strangely `waifuc[gpu]` with `FirstNSelectAction()` seems to perform faster on the CPU, and `dghs-imgutils[gpu]` with `ccip_difference` performs a lot faster on the GPU.

**Comment by shimizu-izumi** [comment]
Thanks for thr link @AnAncientForce I will try it ehen I have the time and close this issue if it helps me to get it working.

**Comment by shimizu-izumi** [comment]
Holy sh*t, I can't believe that worked.
https://www.youtube.com/watch?v=KC9-9L7FgPc

**Comment by shimizu-izumi** [comment]
Great, back to the same issue and the video is unavailable @AnAncientForce

**Comment by AnAncientForce** [comment]
@shimizu-izumi I noticed that too and honestly couldn't get it to work again because I never downloaded the video or took notes. In the mean time I switched back to Linux which eliminated the issue entirely (`sudo pacman -S cudnn`, automatically handles system paths).

**Comment by shimizu-izumi** [comment]
Great, I even added stuff manually to the path and still get an error but it still runs?
